# ========================================================================
# pytest.ini - DEFAULT / API CONFIGURATION RUNNER
# ========================================================================

[pytest]
addopts =
    -v
    --html=reports/framework_report.html
    --self-contained-html
    --capture=tee-sys
    --alluredir=reports/allure-results
    --color=no
    --clean-alluredir

log_cli = False
testpaths = tests

markers =
    ui: UI related tests
    sanity: Quick smoke checks for critical application sanity paths
    regression: Complete end-to-end regression validation suites
    login: Authentication specific validation suites
    api: API specific validation suites