# ========================================================================
# pytest.ini - PYTEST ENGINE CONFIGURATION RUNNER
# ========================================================================

[pytest]
# Default command-line arguments applied automatically upon running 'pytest'
addopts =
    -v
    --browser=chromium
    --headless=False
    --base-url=https://tutorialsninja.com/demo
    --video=retain-on-failure
    --screenshot=only-on-failure
    --tracing=retain-on-failure
    --html=reports/framework_report.html
    --self-contained-html
    --capture=tee-sys
    --alluredir=reports/allure-results
    --color=no
    --clean-alluredir

# Default directory path where Pytest will look for automated test files
testpaths = tests

# Custom Grouping Markers (Categorizes your tests for clean execution)
markers =
    ui: UI related tests
    api: API specific validation suites
    sanity: Quick smoke checks for critical application sanity paths
    regression: Complete end-to-end regression validation suites
    login: Authentication specific validation suites